#!/usr/bin/env python3
"""Small ARIES simulator for driver integration tests.

The simulator changes only in-memory pulse coordinates for validated APS/RPS
and Method 10 ORG commands; it never connects to physical hardware.
"""

import argparse
import socket


def send_line(connection: socket.socket, text: str) -> None:
    """Send one ARIES response using the controller's CRLF delimiter."""
    connection.sendall(text.encode("ascii") + b"\r\n")


def serve(host: str, port: int) -> None:
    """Accept one IOC connection and answer its read-only discovery commands."""
    # Axis 1 applies WSY normally. Axis 2 deliberately acknowledges WSY but
    # retains its value so the driver's mandatory RSY readback can catch it.
    origin_methods = {1: 4, 2: 10}
    positions = {axis: axis * 100 for axis in range(1, 7)}
    moving = {axis: False for axis in range(1, 7)}
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as listener:
        listener.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        listener.bind((host, port))
        listener.listen(1)
        print(f"READY {host}:{port}", flush=True)

        connection, _ = listener.accept()
        with connection:
            receive_buffer = b""
            while True:
                chunk = connection.recv(4096)
                if not chunk:
                    return
                receive_buffer += chunk

                # TCP is a byte stream: a recv() may contain a partial command
                # or several commands, so split only after a complete CRLF.
                while b"\r\n" in receive_buffer:
                    raw_command, receive_buffer = receive_buffer.split(b"\r\n", 1)
                    command = raw_command.decode("ascii", errors="strict")

                    if command == "IDN":
                        # Reproduce asynchronous error and warning events
                        # arriving before the response currently awaited by
                        # the IOC. No REM/RAX release is generated by the IOC.
                        send_line(connection, "E\tSYS\t5")
                        send_line(connection, "W\tSYS\t52")
                        send_line(connection, "C\tIDN\tARIES\t1\t4\t3")
                    elif command == "RAX":
                        # Six connected devices/axes are sufficient to verify
                        # that the driver parses the second numeric field.
                        print("RECEIVED RAX", flush=True)
                        send_line(connection, "C\tRAX\t6\t6\t11111100")
                    elif command.startswith("RDP") and command[3:].isdigit():
                        axis = int(command[3:])
                        if 1 <= axis <= 6:
                            send_line(connection, f"C\tRDP{axis}\t{positions[axis]}")
                        else:
                            send_line(connection, f"E\tRDP{axis}\t120")
                    elif command.startswith("STR") and command[3:].isdigit():
                        axis = int(command[3:])
                        if 1 <= axis <= 6:
                            # stopped, no EMG, ORG on/NORG off, no limits,
                            # inside software limit, correction range valid
                            # Axis 6 keeps physical EMG active so guarded REM
                            # is rejected. Axis 1 stays clear for HOME preflight.
                            emergency = 1 if axis == 6 else 0
                            drive = 1 if moving[axis] else 0
                            send_line(connection, f"C\tSTR{axis}\t{drive}\t{emergency}\t2\t0\t0\t1")
                        else:
                            send_line(connection, f"E\tSTR{axis}\t120")
                    elif command.startswith("ROG") and command[3:].isdigit():
                        axis = int(command[3:])
                        if 1 <= axis <= 6:
                            send_line(connection, f"C\tROG{axis}\t1")
                        else:
                            send_line(connection, f"E\tROG{axis}\t120")
                    elif command.startswith("STP") and command.endswith("/0"):
                        axis_text = command[3:-2]
                        if axis_text.isdigit() and 1 <= int(axis_text) <= 6:
                            # Log the exact wire command so the runner verifies
                            # that routine STOP never selects emergency mode 1.
                            print(f"RECEIVED {command}", flush=True)
                            moving[int(axis_text)] = False
                            send_line(connection, f"C\tSTP{axis_text}")
                        else:
                            send_line(connection, f"E\tSTP{axis_text}\t120")
                    elif command == "WTB1/0/100/1000/20/20/2":
                        # WTB updates table data but never starts motion.
                        print(f"RECEIVED {command}", flush=True)
                        send_line(connection,
                                  "C\tWTB1\t0\t100\t1000\t20\t20\t2\t180\t180")
                    elif command.startswith("WTB1/0/"):
                        # Accept other validated table-0 values generated from
                        # motor record VELO/VBAS/ACCL during move testing.
                        print(f"RECEIVED {command}", flush=True)
                        fields = command[4:].split("/")
                        send_line(connection, "C\tWTB1\t" + "\t".join(fields) +
                                  "\t180\t180")
                    elif command == "RSY1/16":
                        # Axis-specific maximum speed ceiling used before WTB.
                        print(f"RECEIVED {command}", flush=True)
                        send_line(connection, "C\tRSY1\t16\t50000")
                    elif command in ("RSY1/2", "RSY2/2"):
                        print(f"RECEIVED {command}", flush=True)
                        axis = int(command[3])
                        send_line(connection,
                                  f"C\tRSY{axis}\t2\t{origin_methods[axis]}")
                    elif command.startswith("WSY") and "/2/" in command:
                        axis_text, method_text = command[3:].split("/2/", 1)
                        if axis_text.isdigit() and method_text.isdigit():
                            axis = int(axis_text)
                            method = int(method_text)
                            print(f"RECEIVED {command}", flush=True)
                            if axis == 1:
                                origin_methods[axis] = method
                            send_line(connection, f"C\tWSY{axis}\t2")
                        else:
                            send_line(connection, f"E\tWSY\t4")
                    elif command == "ORG1/0/1":
                        # Method 10 changes coordinates but performs no drive.
                        print(f"RECEIVED {command}", flush=True)
                        positions[1] = 0
                        send_line(connection, "C\tORG1")
                    elif command == "ORG2/0/1":
                        # This indicates a regression: the mock acknowledges
                        # WSY2 but its RSY2 readback deliberately remains 10.
                        print(f"RECEIVED {command}", flush=True)
                        send_line(connection, "C\tORG2")
                    elif command.startswith("APS1/0/") and command.endswith("/1"):
                        target_text = command[len("APS1/0/"):-2]
                        if target_text.lstrip("-").isdigit():
                            positions[1] = int(target_text)
                            print(f"RECEIVED {command}", flush=True)
                            send_line(connection, "C\tAPS1")
                        else:
                            send_line(connection, "E\tAPS1\t103")
                    elif command.startswith("RPS1/0/") and command.endswith("/1"):
                        amount_text = command[len("RPS1/0/"):-2]
                        if amount_text.lstrip("-").isdigit():
                            positions[1] += int(amount_text)
                            print(f"RECEIVED {command}", flush=True)
                            send_line(connection, "C\tRPS1")
                        else:
                            send_line(connection, "E\tRPS1\t103")
                    elif command in ("FRP1/0/0", "FRP1/0/1"):
                        # Continuous motion is represented by STR drive=1
                        # until the motor record releases JOG and sends STP/0.
                        moving[1] = True
                        print(f"RECEIVED {command}", flush=True)
                        send_line(connection, "C\tFRP1")
                    elif command.startswith("WRP1/"):
                        value_text = command[len("WRP1/"):]
                        if value_text.lstrip("-").isdigit():
                            value = int(value_text)
                            if -134217728 <= value <= 134217727:
                                positions[1] = value
                                print(f"RECEIVED {command}", flush=True)
                                send_line(connection, "C\tWRP1")
                            else:
                                send_line(connection, "E\tWRP1\t102")
                        else:
                            send_line(connection, "E\tWRP1\t102")
                    elif command == "REM":
                        # Logging makes an unsafe driver regression visible;
                        # this branch must not be reached while EMG is active.
                        print("RECEIVED REM", flush=True)
                        send_line(connection, "E\tREM\t801")
                    else:
                        send_line(connection, f"E\t{command}\t4")


def main() -> None:
    parser = argparse.ArgumentParser(description="Read-only mock ARIES server")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=22321)
    arguments = parser.parse_args()
    serve(arguments.host, arguments.port)


if __name__ == "__main__":
    main()
